name: ci

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "24 8 * * SAT"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.x
      - run: |
          deno fmt --check
          deno test -A
